### ISSUE TITLE
page.corszitesForQuery is undefined

### ISSUE THREAD

**Issue by slrslr** [blurHY/Horizon#7]
**Describe the bug**
The Firefox Developer Console (F12) shows this on Horizon page load:

TypeError: page.corszitesForQuery is undefined[Learn More] horizon.js:150:1

And when i search for something, it does nothing.

I think on Windows it also not worked and in 0list or ZeroTalk thread was same or similar issue with a screenshot.

**Comment by blurHY** [comment]
Fixed in 5133200aea8927e06d7de4f470980419ba02d0a3

**Comment by slrslr** [comment]
Maybe You have not yet applied changes on the site as the error is still there.

These are dev. console log lines when i load the page and try to do a search:

![2018-09-12-133238_1024x768_scrot](https://user-images.githubusercontent.com/6596726/45422535-c31fff00-b690-11e8-9d79-63dcae773f10.png)

**Comment by blurHY** [comment]
@slrslr 
You are not using the latest version

**Comment by slrslr** [comment]
I clicked "Check files" and "update" and did Ctrl+F5 already before i sent the previous screenshot with errors.. So i did it again now, update ZeroNet, i see i am runing probably latest available: r3597
Then i do (Check files, Update, Ctrl+F5 on Horizon site), but errors still there.

TypeError: page.corszitesForQuery is now on line: 145:1 , not previous 150:1
appears during page load

The second type error, (same like in screenshot) appears when i try to search and this time on line: 240:1

My Firefox is 62.0 32 bit on Ubuntu 16.04

**Comment by blurHY** [comment]
I'm testing it in firefox with a blank zeronet

**Comment by blurHY** [comment]
Uh,it works well on firefox and chrome.

**Comment by slrslr** [comment]
I also tried in Chromium (not chrome, i am on Ubuntu Linux atm. should return to Windows next week):

![horizon-chromium-errors](https://user-images.githubusercontent.com/6596726/45586491-82c2ba00-b8f8-11e8-8126-55d59af9f502.jpg)

I seen 2 other user also reported problem with search (nothing happening when hitting enter), @blurHY are you sure you signed & published the changes? Did you tried to use Horizon on different computer/device?

**Comment by blurHY** [comment]
Please directlt download from github.When i publish it,it says published to 1/1 peer.So it will be slow to receive the update,especially you are not in China,i guess.

**Comment by blurHY** [comment]
Oh,i know.That's a bug that just new user would found it.
So i should clear the cache of zeronet of that zite
Thanks for the report.

**Comment by blurHY** [comment]
@slrslr It should be fixed now

**Comment by slrslr** [comment]
I see Horizon site updated around the time of your post, so on page load in console is:
[Show/hide message details.] TypeError: page.corszites_list is not iterable[Learn More] horizon.js:1053:1

In log file i found these related entries in the time i loaded the site:
[11:54:40] Site:1CjMsv..uxBn DbQuery error: no such table: search_zite
[11:54:49] Site:1CjMsv..uxBn DbQuery error: no such table: phrases
[11:54:49] Site:1CjMsv..uxBn DbQuery error: no such table: phrases

The engine message "Collecting more infomation" is taking several minutes and shows no results, so i deleted the Horizon site and revisit it to download it a new.

It is loading quite long time on my old PC (meaning green progress bar on the top and high CPU utilization of the Zeronet's start.py process).

In the log i see:
12:00:43] - UiWSGIHandler error: error: [Errno 32] Broken pipe in UiServer.py line 40 > pywsgi.py line 871 > pywsgi.py line 866 > _socket2.py line 412 > _socket2.py line 351 > _socket2.py line 320

several times. It asked me read permissions to ZeroTalk etc. i seen several more UiWSGIHandler error.

But after like 5 minutes the green downloading bar on Horizon site completed (page was loaded) and i tried search, it took like 5 seconds (not showed any information that the search is in progress, which may be improved so user knows something is going on during waiting) and then showed results and console shows no error at all! :)

I closed the page and reopened it confirming to increase site storage limit

The developer console show this on page load:
`[Wrapper] Setting title to Horizon - ZeroNet
all.js:1699:14
[Show/hide message details.] **TypeError: page.corszitesForQuery is undefined[Learn More] horizon.js:145:1**
f
http://127.0.0.1:43110/1CjMsvhJ2JsV4B5qo3FDHnF3mvRCcHuxBn/horizon.js:145:1
initFollowedCORS
http://127.0.0.1:43110/1CjMsvhJ2JsV4B5qo3FDHnF3mvRCcHuxBn/horizon.js:156:3
initCORS/</</<
http://127.0.0.1:43110/1CjMsvhJ2JsV4B5qo3FDHnF3mvRCcHuxBn/horizon.js:135:6
onMessage
http://127.0.0.1:43110/1CjMsvhJ2JsV4B5qo3FDHnF3mvRCcHuxBn/js/ZeroFrame.js:38:17
connect/<
http://127.0.0.1:43110/1CjMsvhJ2JsV4B5qo3FDHnF3mvRCcHuxBn/js/ZeroFrame.js:29:49
[ZeroFrame] Unknown incoming message: undefined ZeroFrame.js:98:9
Use of Mutation Events is deprecated. Use MutationObserver instead. content.js:30:251
[Wrapper] Invalid message: 
Object { msg: "dh5a:send-msg-to-frames", msgToSend: {…} }
all.js:1699:14
[Wrapper] Invalid message: 
Object { msg: "dh5a:input-recieved", event: "mousedown", value: true }
all.js:1699:14
hideProgress
all.js:609:7
[Wrapper] Invalid message: 
Object { msg: "dh5a:send-msg-to-frames", msgToSend: {…} }
all.js:1699:14
[Wrapper] Invalid message: 
Object { msg: "dh5a:input-recieved", event: "mousedown", value: false }
all.js:1699:14
hideProgress`

Then when i try to search, there is another TypeError:
TypeError: page.corszitesForQuery is undefined[Learn More] horizon.js:240:1
and no results, no reaction on submitting search query.

It is strange that first time it worked, but after closing page and open again, it again not working.

Interesting is that on ZeroHello, Horizon site shows last updated 9 hours ago, while before site delete the update was much earlier. So i now tried to Check files and Update, but nothing updated, refreshed ZeroHello still shows last update of Horizon 9 hours ago. Maybe there is too low number of peers who have up to date site, i am passive peer myself (closed port). Trackers 13/15

btw. [here](https://pastebin.com/Q0e8M4xN) is the zeronet log for the time of deleting and re-downloading site from peers to this moment.

**Comment by blurHY** [comment]
These bug should be fixed i think,uh
- page.corszites_list is not iterable[Learn More] horizon.js:1053:1
- page.corszitesForQuery is undefined[Learn More] horizon.js:145:

> In log file i found these related entries in the time i loaded the site:
> [11:54:40] Site:1CjMsv..uxBn DbQuery error: no such table: search_zite
> [11:54:49] Site:1CjMsv..uxBn DbQuery error: no such table: phrases
> [11:54:49] Site:1CjMsv..uxBn DbQuery error: no such table: phrases

I think the file is not downloaded completely.So the table is missing.I uploaded the json files just now,then you can use the file on the github.

> In the log i see:
> 12:00:43] - UiWSGIHandler error: error: [Errno 32] Broken pipe in UiServer.py line 40 > pywsgi.py line 871 > pywsgi.py line 866 > _socket2.py line 412 > _socket2.py line 351 > _socket2.py line 320

That should be a bug of zeronet,please report it.

> several times. It asked me read permissions to ZeroTalk etc. i seen several more UiWSGIHandler error.

That's for cors search(search in zerotalk)

> But after like 5 minutes the green downloading bar on Horizon site completed (page was loaded) and i tried search, it took like 5 seconds (not showed any information that the search is in progress, which may be improved so user knows something is going on during waiting) and then showed results and console shows no error at all! :)

[Todo added](https://github.com/blurHY/Horizon/projects/1#card-13028736)
 
> I closed the page and reopened it confirming to increase site storage limit

Yeah,it's 26MB

> Interesting is that on ZeroHello, Horizon site shows last updated 9 hours ago, while before site delete the update was much earlier. So i now tried to Check files and Update, but nothing updated, refreshed ZeroHello still shows last update of Horizon 9 hours ago. Maybe there is too low number of peers who have up to date site, i am passive peer myself (closed port). Trackers 13/15

I'm a passive peer too,so would take a long time to receive the update
